// Create a random walk where the step size (how far the object moves in a given direction) is generated by a normal Gaussian distribution

import java.util.Random;

Random generator;
Walker w;

class Walker {
  int x;
  int y;

  Walker() {
    x = width/2;
    y = height/2;
  }

  void display () {
    stroke(255);
    point(x, y);
  }

  void step() {
    int choice = int(random(2));
    int stepSize = (int) (generator.nextGaussian()*10);

    switch (choice) {
      case 0: choice = 0;
              x=x+stepSize;
      case 1: choice = 2;
              y=y+stepSize;
    }
  }
}

void setup() {
  size(640, 320);
  background(25, 25, 25);
  generator = new Random();
  w = new Walker();
}

void draw() {
  w.step();
  w.display();
}
